# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/oneplus8pro/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    bluetooth \
    cmnlib \
    cmnlib64 \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    logo \
    modem \
    multiimgoem \
    qupfw \
    storsec \
    tz \
    uefisecapp \
    xbl_config \
    xbl
